### ISSUE TITLE
complex prefileter error

### ISSUE THREAD

**Issue by yuqiyuqitan** [Teichlab/cellphonedb#123]
Hi,
 
Thanks for creating the tool! I am trying to pipe my expression and metadata from R to cellphonedb. But no matter how I transformed the expression data (raw, downsample, downsample and log-transformed) it seems to stuck at prefilter step of cellphonedb analysis. Could you help me to pin down where the error is coming from?

Thank you!
Yuqi
###################
This is how I format the data for output in R:
dim(sampTab_db)
[1] 266   2

dim(expDat)
[1] 56391   266

write.table(sampTab_db[,c("Cell", "cell_type")], file = "sampTab.txt",row.names=FALSE, sep = "\t")
write.table(data.frame("Gene" = rownames(expDat), expDat), file = "expDat.txt", row.names = FALSE, sep = "\t")

###################
here is my cellphonedb output
(cpdb-venv) MacBook-Pro:test YT$ cellphonedb method analysis sampTab.txt expDat.txt 
[ ][APP][24/09/19-10:25:52][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][24/09/19-10:25:52][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][24/09/19-10:25:52][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][24/09/19-10:25:52][INFO] Using custom database at /Users/YT/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][24/09/19-10:25:52][INFO] Launching Method cpdb_analysis_local_method_launcher
[ ][APP][24/09/19-10:25:52][INFO] Launching Method _set_paths
[ ][APP][24/09/19-10:25:52][INFO] Launching Method _load_meta_counts
[ ][CORE][24/09/19-10:25:54][INFO] Launching Method cpdb_method_analysis_launcher
[ ][CORE][24/09/19-10:25:54][INFO] Launching Method _counts_validations
[ ][CORE][24/09/19-10:25:54][INFO] [Non Statistical Method] Threshold:0.1 Precission:3
[ ][CORE][24/09/19-10:25:54][INFO] Running Simple Prefilters
[ ][CORE][24/09/19-10:25:54][INFO] [Non Statistical Method] Threshold:0.1 Precision:3
[ ][CORE][24/09/19-10:25:54][INFO] Running Complex Prefilters
[ ][APP][24/09/19-10:25:54][ERROR] Unexpected error
Traceback (most recent call last):
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 207, in analysis
    subsampler,
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 98, in cpdb_analysis_local_method_launcher
    subsampler)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 113, in cpdb_method_analysis_launcher
    result_precision)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_method.py", line 35, in call
    result_precision)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_complex_method.py", line 29, in call
    complex_compositions, counts_data)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_complex_method.py", line 329, in prefilters
    complexes, complex_compositions)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_complex_method.py", line 391, in get_involved_complex_from_counts
    drop_duplicates=False)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/models/complex/complex_helper.py", line 11, in get_involved_complex_from_protein
    right_on='id_multidata')
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 61, in merge
    validate=validate)
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 551, in __init__
    self.join_names) = self._get_merge_keys()
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 857, in _get_merge_keys
    rk, stacklevel=stacklevel))
  File "/Users/YT/Desktop/test/cpdb-venv/lib/python3.7/site-packages/pandas/core/generic.py", line 1382, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id_multidata'

**Comment by mvento** [comment]
Hi @yuqiyuqitan, 

Can you send us the input files? (or just some rows).

Thanks!

**Comment by yuqiyuqitan** [comment]
sent the data to your email: miquel@ydevs.com

**Comment by mvento** [comment]
Hi @yuqiyuqitan,

Received I will check it asap.

Best

**Comment by rylanci** [comment]
Hello,
I am running into the same error. Was this issue resolved? 

Thanks

**Comment by yuqiyuqitan** [comment]
@rylanci No, I haven't received a solution.

**Comment by mvento** [comment]
Hi @yuqiyuqitan, 

Sorry, I forgot to check it. 

I will check it this week. Sorry for the inconvenience.

Best

**Comment by rylanci** [comment]
Great, I would certainly be interested as well when you do identify the issue.

**Comment by mvento** [comment]
Hi @yuqiyuqitan, 

What R version are you using?

Best

**Comment by yuqiyuqitan** [comment]
@mvento  3.6.1

**Comment by mvento** [comment]
Ok, I will try to update it because I can't install the R dependences with R 3.4.

To resolve it faster, can you send me the csv result files of your script? 

Best

**Comment by Archanayd** [comment]
Hi, 
I am getting the same errors. Any update on how to resolve the issue? 
Thanks

**Comment by Archanayd** [comment]
Ok, so in my case, the error got resolved when I mentioned which count data type I am using, by specifying the parameter, '--counts-data=gene_name'. I think by default it runs on ensemble IDs and my count matrix had genes names.

**Comment by woshilushu** [comment]
> @yuqiyuqitan 
hi yuqi, I have this problem also, completely the same error output, have you solved this problem?

thanks!
