### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by julierodor** [Teichlab/cellphonedb#140]
Hi, 
I have been trying to run cellphonedb but I am having an error.
I am adding below the command line, outputs and details of Input.
Please let me know what to change. 
Thanks in advance,
Julie

cellphonedb method analysis pah.subset.metada.cpdb.txt pah.subset.count.cpdb.txt --counts-data gene_name

## error
/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
[ ][APP][21/01/20-15:24:00][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][21/01/20-15:24:00][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][21/01/20-15:24:00][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][21/01/20-15:24:00][INFO] Using custom database at /home/jrodor2/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][21/01/20-15:24:00][INFO] Launching Method cpdb_analysis_local_method_launcher
[ ][APP][21/01/20-15:24:00][INFO] Launching Method _set_paths
[ ][APP][21/01/20-15:24:00][INFO] Launching Method _load_meta_counts
[ ][CORE][21/01/20-15:24:01][INFO] Launching Method cpdb_method_analysis_launcher
[ ][CORE][21/01/20-15:24:01][INFO] Launching Method _counts_validations
[ ][CORE][21/01/20-15:24:01][INFO] [Non Statistical Method] Threshold:0.1 Precission:3
[ ][CORE][21/01/20-15:24:01][INFO] Running Simple Prefilters
[ ][CORE][21/01/20-15:24:02][INFO] [Non Statistical Method] Threshold:0.1 Precision:3
[ ][CORE][21/01/20-15:24:02][INFO] Running Complex Prefilters
[ ][APP][21/01/20-15:24:02][ERROR] Unexpected error
Traceback (most recent call last):
  File "/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 207, in analysis
    subsampler,
  File "/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 98, in cpdb_analysis_local_method_launcher
    subsampler)
  File "/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 113, in cpdb_method_analysis_launcher
    result_precision)
  File "/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/cellphonedb/src/core/methods/cpdb_analysis_method.py", line 41, in call
    deconvoluted.drop_duplicates(inplace=True)
  File "/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/pandas/core/frame.py", line 4331, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/home/jrodor2/cpdb-venv/lib/python3.5/site-packages/pandas/core/frame.py", line 4385, in duplicated
    labels, shape = map(list, zip(*map(f, vals)))
ValueError: not enough values to unpack (expected 2, got 0)

### input #my metadata file looks like this
Cell	cluster
pah3_CGGACACGTTGAGTTC	c3
contA_CACACTCTCTGTTTGT	c1
contA_CTCGTCATCCGTCAAA	c7
pah3_CTCGAGGGTTTGACAC	c0
pah2_TCTCATAAGCGTTCCG	c0
pah2_GAGCAGATCCAAGCCG	c3
pah2_GGCTGGTGTTACAGAA	c0
contB_TCAGCAACATATGGTC	c1
pah1_GCACATATCAAGGTAA	c3

# count table (showing subset 10 rows/5 columns)
Gene	pah3_CGGACACGTTGAGTTC	contA_CACACTCTCTGTTTGT	contA_CTCGTCATCCGTCAAA	pah3_CTCGAGGGTTTGACAC
Rp1	0	0	0	0
Sox17	0	0	0	2.74082443266566
Mrpl15	0	0	0	0
Lypla1	0	0	0	0
Gm37988	0	0	0	0
Tcea1	1.65068087096815	0	1.2849200801299	0
Atp6v1h	0	0	0	1.76357478287235
Rb1cc1	0	0	0	0
4732440D04Rik	0	0	0	0

**Comment by mvento** [comment]
Hi @julierodor,

Can you send me the subset files? Here it seems like you are using spaces instead off tabs as separator character.

Best

**Comment by julierodor** [comment]
Hi,
Here are the 2 files. Saved from R (write.table - sep="\t").
Julie

Julie Rodor

Centre for Cardiovascular Science

University of Edinburgh

Queen’s Medical Research Institute

Edinburgh BioQuarter

47 Little France Crescent

EH16 4TJ, Edinburgh UK

tel: +44 (0)131  242 6745

________________________________

**Comment by mvento** [comment]
Hi,

It seems like you are using space as a separator. If you are using csv
extension (.csv), please use commas. If you are going to use tabs, please
use txt extension (.txt).

Space as a separator is not supported.

Best

**Comment by yurasong** [comment]
Hello!
I also faced exactly same error, although I have used the files with tab-deliminated txt files. Do you have any further recommendations? 

Thanks!

**Comment by JoanaBSilvestre** [comment]
Hi, I have tried with comma separated csv files and tab separated txt files and had the same error.
Are there any recommendations on how to solve it?
Thank you
