### ISSUE TITLE
fail to install cellphonedb

### ISSUE THREAD

**Issue by yumingliutroy** [Teichlab/cellphonedb#142]
when I use "pip" for installing cellphonedb in Win7 or Win10, I just encountered a problem referring to "rpy2" package.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/sqlalchemy/
    ERROR: Command errored out with exit status 1:
     command: 'D:\Users\Ming\PycharmProjects\untitled\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ming\\AppData\\Local\\Temp\\pycharm-packaging\\rpy2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ming\\AppData\\Local\\Temp\\pycharm-packaging\\rpy2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Ming\AppData\Local\Temp\pycharm-packaging\rpy2\pip-egg-info'
         cwd: C:\Users\Ming\AppData\Local\Temp\pycharm-packaging\rpy2\
    Complete output (92 lines):
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    warning: build_py: byte-compiling is disabled, skipping.
    
    warning: install_lib: byte-compiling is disabled, skipping.
    
    zip_safe flag not set; analyzing archive contents...
    
    Installed c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaN' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaReal' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaInt' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BlankString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BlankScalarString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_GlobalEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_EmptyEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseNamespace' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseNamespaceRegistry' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NilValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_UnboundValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_MissingArg' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_ClassSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NameSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_DimSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    Traceback (most recent call last):
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py", line 305, in _parse
        ast = _get_parser().parse(fullcsource)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg\pycparser\c_parser.py", line 152, in parse
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg\pycparser\ply\yacc.py", line 331, in parse
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg\pycparser\ply\yacc.py", line 193, in call_errorfunc
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg\pycparser\c_parser.py", line 1848, in p_error
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\pycparser-2.19-py3.7.egg\pycparser\plyparser.py", line 67, in _parse_error
    pycparser.plyparser.ParseError: <cdef source string>:23:5: before: blah1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ming\AppData\Local\Temp\pycharm-packaging\rpy2\setup.py", line 184, in <module>
        'rpy2': ['doc/source/rpy2_logo.png', ]}
      File "D:\Users\Ming\PycharmProjects\untitled\venv\lib\site-packages\setuptools-39.1.0-py3.7.egg\setuptools\__init__.py", line 129, in setup
      File "D:\Users\Ming\Anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "D:\Users\Ming\PycharmProjects\untitled\venv\lib\site-packages\setuptools-39.1.0-py3.7.egg\setuptools\dist.py", line 363, in __init__
      File "D:\Users\Ming\Anaconda3\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "D:\Users\Ming\PycharmProjects\untitled\venv\lib\site-packages\setuptools-39.1.0-py3.7.egg\setuptools\dist.py", line 519, in finalize_options
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "rpy/_rinterface_cffi_build.py", line 546, in <module>
        """ if os.name == 'nt' else ''
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py", line 358, in parse
        self._internal_parse(csource)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py", line 363, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py", line 307, in _parse
        self.convert_pycparser_error(e, csource)
      File "c:\users\ming\appdata\local\temp\pycharm-packaging\rpy2\.eggs\cffi-1.13.2-py3.7-win-amd64.egg\cffi\cparser.py", line 336, in convert_pycparser_error
        raise CDefError(msg)
    cffi.CDefError: cannot parse "blah1 ReadConsole;"
    <cdef source string>:23:5: before: blah1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

What should I do and thank you so much!

**Comment by mvento** [comment]
Hi @yumingliutroy, 

Windows 10 is not directly supported by CellPhoneDB team because rpy2 library is not available in Windows. 

Please use [docker image](https://hub.docker.com/r/ydevs/cellphonedb) to run CellPhoneDB on Windows.

Best
