### ISSUE TITLE
Error: SyntaxError

### ISSUE THREAD

**Issue by weiiioyo** [Teichlab/cellphonedb#191]
Hi, 
I have downloaded CellPhoneDB 2.1.4, and try to run the pacakage, but I get the following error. 
command line:  /work1/software/x86_64.1/cellphonedb/2.1.4/bin/cellphonedb
Error 👍 
/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_mean and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot part of the private API.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/bin/cellphonedb", line 5, in <module>
    from cellphonedb.cellphonedb_cli import cli
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/cellphonedb_cli.py", line 6, in <module>
    from cellphonedb.src.api_endpoints.terminal_api.database_terminal_api_endpoints import database_terminal_commands
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/src/api_endpoints/terminal_api/database_terminal_api_enline 8, in <module>
    from cellphonedb.src.api_endpoints.terminal_api.tools_terminal_api_endpoints.tools_terminal_commands import \
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/src/api_endpoints/terminal_api/tools_terminal_api_endpo, in <module>
    from cellphonedb.src.app.cellphonedb_app import output_dir, data_dir
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/src/app/cellphonedb_app.py", line 3, in <module>
    from cellphonedb.src.app.flask.flask_cellphonedb import CellphonedbFlask
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/src/app/flask/flask_cellphonedb.py", line 1, in <module
    from cellphonedb.src.core.CellphonedbSqlalchemy import CellphonedbSqlalchemy
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/src/core/CellphonedbSqlalchemy.py", line 12, in <module
    from cellphonedb.src.core.database.sqlalchemy_repository.InteractionRepository import InteractionRepository
  File "/work1/software/x86_64.1/cellphonedb/2.1.4/lib/python3.5/site-packages/cellphonedb/src/core/database/sqlalchemy_repository/InteractionRepo
    multidata_expanded: pd.DataFrame = self.database_manager.get_repository('multidata').get_all_expanded(
                      ^
SyntaxError: invalid syntax

And I delete the ': pd.DataFrame' as prompted, and it works.  So I want to know if I handled it correctly?

**Comment by weiiioyo** [comment]
I have re-installed the pacakge, and it didn't report the error.
