### ISSUE TITLE
ValueError: You are trying to merge on int64 and object columns

### ISSUE THREAD

**Issue by aditisk** [Teichlab/cellphonedb#21]
Hello, I am getting this error when I am trying to run cellphonedb with our dataset. I am not sure what this error means and what is triggering it. Any comments/help would be appreciated. Thanks.

[ ][CORE][21/03/19-16:39:15][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][APP][21/03/19-16:39:15][INFO] Launching Method cpdb_analysis_local_method_launcher
[ ][APP][21/03/19-16:39:15][INFO] Launching Method _set_paths
[ ][APP][21/03/19-16:39:15][INFO] Launching Method _load_meta_counts
[ ][CORE][21/03/19-16:53:50][INFO] Launching Method cpdb_method_analysis_launcher
[ ][CORE][21/03/19-16:53:50][INFO] Launching Method _counts_validations
[ ][CORE][21/03/19-16:54:41][INFO] [Non Statistical Method] Threshold:0.1 Precission:3
[ ][CORE][21/03/19-16:54:41][INFO] Running Simple Prefilters
[ ][CORE][21/03/19-16:54:57][INFO] [Non Statistical Method] Threshold:0.1 Precision:3
[ ][CORE][21/03/19-16:54:57][INFO] Running Complex Prefilters
[ ][APP][21/03/19-16:54:57][ERROR] Unexpected error
Traceback (most recent call last):
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", li$
    result_precision,
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 84, in cpdb_analysis_local_method_launcher
    result_precision)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 92, in cpdb_method_analysis_launcher
    result_precision)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_method.py", line 29, in call
    result_precision)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_complex_method.py", line 25, in call
    complex_compositions)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_analysis_complex_method.py", line 290, in prefilters
    counts_multidata = cluster_counts_filter.filter_by_gene(counts, genes)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/cellphonedb/src/core/models/cluster_counts/cluster_counts_filter.py", line 11, in filter_by_gene
    clusters_filtered = pd.merge(cluster_counts, genes, left_on='gene', right_on=right_column)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 61, in merge
    validate=validate)
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 555, in __init__
    self._maybe_coerce_merge_keys()
  File "/ihome/crc/install/python/anaconda3.7-5.3.1_genomics/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 983, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

**Comment by mvento** [comment]
Hi @aditisk,

Thanks for using CellPhoneDB!

Are you using the last version of the package?

please, try to run:
```
pip uninstall -y cellphonedb
pip install --no-cache-dir cellphonedb
```

Thanks!

**Comment by cartal** [comment]
Hi, I'm also getting: 

`ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat`

I'm using `cellphonedb==2.1.1` and I get the same error after followed your instructions as above; any ideas?
