### ISSUE TITLE
How to create user's own database with a new interaction list file??

### ISSUE THREAD

**Issue by Sara0201Tao** [Teichlab/cellphonedb#234]
Hi ,

Thank you very much for this package. After trying the default database, I have some new LR interaction pairs from literatures and want to creat a new database to test. Unfortunately, I came across to some problems and don’t know how to slove it. what I want to is, what file and what format should I prepare for the command [cellphonedb database generate]?

The command what I wrote is : cellphonedb database generate --user-interactions CellP_italk_LR.csv --user-interactions-only

the CellP_italk_LR.csv looks like this:
<img width="634" alt="屏幕快照 2020-12-01 下午12 47 29" src="https://user-images.githubusercontent.com/64693543/100698508-9bcdbd80-33d3-11eb-88af-e0464ac6cba0.png">

and the results and error it returns is as follows:
[ ][APP][01/12/20-12:02:22][WARNING] Output directory (/home/mztao/cellp_test/new_database/out) exist and is not empty. Result can overwrite old results
read local ensembl file
read local uniprot file
/home/mztao/cellp_test/lib/python3.7/site-packages/cellphonedb/src/core/generators/gene_generator.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  ensembl_db_filtered.dropna(inplace=True)
[ ][APP][01/12/20-12:02:38][WARNING] Output directory (/home/mztao/cellp_test/new_database/out) exist and is not empty. Result can overwrite old results
[ ][APP][01/12/20-12:02:38][WARNING] Output directory (/home/mztao/cellp_test/new_database/out) exist and is not empty. Result can overwrite old results
[ ][APP][01/12/20-12:02:38][WARNING] Output directory (/home/mztao/cellp_test/new_database/out) exist and is not empty. Result can overwrite old results
[ ][APP][01/12/20-12:02:38][WARNING] Output directory (/home/mztao/cellp_test/new_database/out) exist and is not empty. Result can overwrite old results
[ ][APP][01/12/20-12:02:39][WARNING] Output directory (/home/mztao/cellp_test/new_database/out) exist and is not empty. Result can overwrite old results
Traceback (most recent call last):
  File "/home/mztao/cellp_test/bin/cellphonedb", line 11, in <module>
    sys.exit(cli())
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/database_terminal_api_endpoints/database_terminal_commands.py", line 105, in generate
    ctx.invoke(filter_all, input_path=output_path, result_path=result_path)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mztao/cellp_test/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/tools_terminal_api_endpoints/tools_terminal_commands.py", line 342, in filter_all
    ', '.join(rejected_members)))
TypeError: sequence item 705: expected str instance, float foun

Thanks for your time and llok forward to you reply~

Sara

**Comment by martin-jeremy** [comment]
+1

**Comment by luzgaral** [comment]
I recommend you to use uniprot ids, like in the original file:
https://raw.githubusercontent.com/Teichlab/cellphonedb-data/master/data/sources/interaction_curated.csv

Note that the lack of uniprot is interpreted as a complex, and then a complex file is required.


Check **CellPhoneDB Lists Curated** https://www.cellphonedb.org/downloads for examples of file formats to generate the database
https://www.cellphonedb.org/downloads
