### ISSUE TITLE
Could not run example data using conda

### ISSUE THREAD

**Issue by wwn7268** [Teichlab/cellphonedb#330]
Hi CellPhoneDB,

When I run cellphonedb with example data, it cannot get the results. What is the problem?
 
[ ][CORE][05/07/21-23:42:49][INFO] Building Pvalues result
[ ][CORE][05/07/21-23:42:50][INFO] Building Simple results
[ ][CORE][05/07/21-23:42:51][INFO] [Cluster Statistical Analysis Complex] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:4 Precision:3
[ ][CORE][05/07/21-23:42:51][INFO] Running Complex Prefilters
[ ][APP][05/07/21-23:42:51][ERROR] Unexpected error
Traceback (most recent call last):
  File "g:\anaconda\envs\cpdb\lib\site-packages\cellphonedb\src\api_endpoints\terminal_api\method_terminal_api_endpoints\method_terminal_commands.py", line 66, in statistical_analysis
    result_precision
  File "g:\anaconda\envs\cpdb\lib\site-packages\cellphonedb\src\local_launchers\local_method_launcher.py", line 55, in cpdb_statistical_analysis_local_method_launcher
    result_precision)
  File "g:\anaconda\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\method_launcher.py", line 62, in cpdb_statistical_analysis_launcher
    result_precision)
  File "g:\anaconda\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_method.py", line 41, in call
    result_precision)
  File "g:\anaconda\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 41, in call
    cells_names)
  File "g:\anaconda\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 416, in get_complex_significative
    complex_more_significative_protein = pd.Series(data='', index=complex_counts['name_complex'].drop_duplicates())
  File "g:\anaconda\envs\cpdb\lib\site-packages\pandas\core\series.py", line 275, in __init__
    raise_cast_failure=True)
  File "g:\anaconda\envs\cpdb\lib\site-packages\pandas\core\series.py", line 4149, in _sanitize_array
    value, len(index), dtype)
  File "g:\anaconda\envs\cpdb\lib\site-packages\pandas\core\dtypes\cast.py", line 1201, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

**Comment by prete** [comment]
Hi @wwn7268 first thing to rule out issues is package versions. Could you please confirm your python (`python -V`), CellPhoneDB, pandas and numpy versions (`pip show cellphonedb pandas numpy`)?

**Comment by wwn7268** [comment]
Hi, 

Thank you. I have checked my package versions.
Python 3.7.10
CellphoneDB 1.1.0
numpy 1.21.0
pandas 0.23.4

Still have the same problem. So what version should I choose?

**Comment by prete** [comment]
Hi, you're using an outdated version of CellphoneDB. I'd recommend you update to the latest one (2.1.7) using `pip install -U cellphonedb`.

**Comment by wwn7268** [comment]
Hi, I have tried: pip install -U CellphoneDB. It still cannot update into the new version. It seems I failed to install it.

Using cached rpy2-3.0.5.tar.gz (117 kB)
    ERROR: Command errored out with exit status 1:
 command: 'C:\Users\Tommy\miniconda3\envs\cpdb\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wangw\\AppData\\Local\\Temp\\pip-install-5uhsa88z\\rpy2_6e9ec3afec1e4bff89454a3d8a0ef104\\setup.py'"'"'; __file__='"'"'C:\\Users\\wangw\\AppData\\Local\\Temp\\pip-install-5uhsa88z\\rpy2_6e9ec3afec1e4bff89454a3d8a0ef104\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\wangw\AppData\Local\Temp\pip-pip-egg-info-accv2c_s'

So how to solve it?

**Comment by prete** [comment]
OK, so you're on Windows. You can try using `environment.yml` as [described in this issue](https://github.com/Teichlab/cellphonedb/issues/270) to get your environment set up.
