### ISSUE TITLE
Continuation of Fix #284 InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by seigfried** [Teichlab/cellphonedb#332]
Hello

My CellphoneDB installation is on a Windows 10 Enterprise Edition system

CellPhoneDB Version: 2.1.7
NumPy Version: 1.20.2
pandas Version: 1.2.4

pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

I think its the same issue addressed in 2.1.7 but the 2.1.7 version also gives me the same error.

```
Traceback (most recent call last):
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\cellphonedb\src\api_endpoints\terminal_api\method_terminal_api_endpoints\method_terminal_commands.py", line 127, in statistical_analysis
    LocalMethodLauncher(cpdb_app.create_app(verbose, database)). \
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\cellphonedb\src\local_launchers\local_method_launcher.py", line 54, in cpdb_statistical_analysis_local_method_launcher
    self.cellphonedb_app.method.cpdb_statistical_analysis_launcher(
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\cellphonedb\src\core\methods\method_launcher.py", line 63, in cpdb_statistical_analysis_launcher
    cpdb_statistical_analysis_method.call(meta,
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_method.py", line 23, in call
    cpdb_statistical_analysis_complex_method.call(meta.copy(),
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 107, in call
    pvalues_result, means_result, significant_means, deconvoluted_result = build_results(
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 201, in build_results
    pvalues_result = pd.concat([interactions_data_result, result_percent], axis=1, join='inner', sort=False)
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\pandas\core\reshape\concat.py", line 298, in concat
    return op.get_result()
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\pandas\core\reshape\concat.py", line 516, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "c:\users\shirgaonkarn\anaconda3\envs\cellphonedb\lib\site-packages\pandas\core\indexes\base.py", line 3171, in get_indexer
    raise InvalidIndexError(
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

Thanks for your efforts!

**Comment by seigfried** [comment]
Sorry I think I misread.

I now realize 2.1.7 just downgrades the pandas to pandas>=1.0.0,<=1.1.4

Thank you again
