### ISSUE TITLE
No CellPhoneDB interacions found in this input.

### ISSUE THREAD

**Issue by monikaramos** [Teichlab/cellphonedb#360]
Hi there. Can someone please help me understand what I am doing to generate this error message? 

[ ][APP][14/01/22-22:02:20][ERROR] Unexpected error
Traceback (most recent call last):
  File "/data/tools/anaconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 150, in statistical_analysis
    debug,
  File "/data/tools/anaconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 75, in cpdb_statistical_analysis_local_method_launcher
    output_path
  File "/data/tools/anaconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 111, in cpdb_statistical_analysis_launcher
    output_path)
  File "/data/tools/anaconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_method.py", line 43, in call
    output_path
  File "/data/tools/anaconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_complex_method.py", line 57, in call
    raise NoInteractionsFound()
cellphonedb.src.core.exceptions.NoInteractionsFound.NoInteractionsFound: No CellPhoneDB interacions found in this input.

Here is my **command**: 
(cpdb) [mramos@hbl23 cellphonedb_test]$ cellphonedb method statistical_analysis kluv_cd40ag_cpdb_meta.txt cpdb_kluv_cd40_counts.txt --project-name=kluv_cd40ag_cpdb --iterations=1000 --threshold=0.10 --counts-data=hgnc_symbol --output-path=/
home/mramos/cellphonedb_test --verbose --threads=6

and this was the log before the error logs 

[ ][APP][14/01/22-22:01:54][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][14/01/22-22:01:54][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][14/01/22-22:01:54][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][14/01/22-22:01:54][INFO] Using custom database at /home/mramos/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][14/01/22-22:01:54][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][14/01/22-22:01:54][INFO] Launching Method _set_paths
[ ][APP][14/01/22-22:01:54][INFO] Launching Method _load_meta_counts
[ ][APP][14/01/22-22:02:19][INFO] Launching Method _check_counts_data
[ ][CORE][14/01/22-22:02:19][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][CORE][14/01/22-22:02:19][INFO] Launching Method _counts_validations
[ ][CORE][14/01/22-22:02:19][INFO] Launching Method get_interactions_genes_complex
[ ][CORE][14/01/22-22:02:20][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:6 

Any help is greatly appreciated. I ensured that my count.txt and meta.txt files were constructed exactly as the sample prep and example files had them as well to fix invalid count errors I initially received.

**Comment by monikaramos** [comment]
Here is an example of what my count.txt input looks like 
![image](https://user-images.githubusercontent.com/85251149/149611799-f8dca508-6d26-4a8e-9c5d-910b07183735.png)

**Comment by monikaramos** [comment]
My genes were not in human hgnc format for anyone else that may have this issue
