### ISSUE TITLE
 TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [nan] of <class 'float'>

### ISSUE THREAD

**Issue by Joifun** [Teichlab/cellphonedb#6]
Dear all,
I ran cellphonedb with my own data but  encountered this error . I have checked the format of my input data but found no difference with the test example.
Thank you!

**Comment by mvento** [comment]
Hi @Joifun,
Can you send us your input data? (or just a part).

Thanks

**Comment by clumeng** [comment]
I got the same error below. email sent with files @mvento   This analysis worked on the web package.

(cpdb-venv) [clumeng@flux-login4 cellphonedb]$ cellphonedb method statistical_analysis meta.csv counts.csv
True
[ ][CORE][29/11/18-09:17:33][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][APP][29/11/18-09:17:33][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][29/11/18-09:17:33][INFO] Launching Method _set_paths
[ ][APP][29/11/18-09:17:33][INFO] Launching Method _load_meta_counts
[ ][CORE][29/11/18-09:17:40][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][CORE][29/11/18-09:17:40][INFO] Launching Method _statistical_analysis_simple_launcher
[ ][CORE][29/11/18-09:17:41][INFO] [Cluster Statistical Analysis Simple] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:4
[ ][CORE][29/11/18-09:17:41][INFO] Running Simple Prefilters
[ ][CORE][29/11/18-09:17:41][INFO] Running Real Simple Analysis
Traceback (most recent call last):
  File "/home/clumeng/cpdb-venv/bin/cellphonedb", line 11, in <module>
    sys.exit(cli())
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 53, in statistical_analysis
    threads)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 45, in cpdb_statistical_analysis_local_method_launcher
    meta, counts, iterations, threshold, threads, debug_seed)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 38, in cpdb_statistical_analysis_launcher
    meta.copy(), count.copy(), iterations, threshold, threads, debug_seed)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 61, in _statistical_analysis_simple_launcher
    debug_seed)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_simple_method.py", line 30, in call
    suffixes=('_1', '_2'))
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py", line 184, in mean_analysis
    interaction_mean = cluster_interaction_mean(cluster_interaction, interaction, clusters['means'], suffixes)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py", line 442, in cluster_interaction_mean
    mean_receptor = means_cluster_receptors[interaction['ensembl{}'.format(suffixes[0])]]
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3115, in get_value
    k = self._convert_scalar_indexer(k, kind='getitem')
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 1663, in _convert_scalar_indexer
    return self._invalid_indexer('label', key)
  File "/home/clumeng/cpdb-venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 1863, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [nan] of <class 'float'>

**Comment by mvento** [comment]
Hi @Joifun and @clumeng, 

We released now the new CellPhoneDB version (v.1.1.0). 
Now we validate some habitual errors in the input data. 

Please upgrade it and contact us if you have any other problem.

Cheers

**Comment by mbassalbioinformatics** [comment]
Hi, recieved the same error when trying to run the current version from github.  Any suggestions please?

**Comment by weiiioyo** [comment]
Maybe your input matrix has a gene named 'NA'.  I had met this error before, and I removed this gene, and it worked.

**Comment by lbjsnower** [comment]
float 类似的解决方案试试，None 还未解决

将index列字符串化即可解决，解决思路如下

> df['name'] = df3['name'].apply(lambda x:str(x))

然后将 df['name'] 设置成index

> df = df.set_index('name',drop=False, append=False, inplace=False,verify_integrity=False)

**Comment by mcap91** [comment]
Same error #253
